### ISSUE TITLE
Add BGPsec Router Keys

### ISSUE THREAD

**Issue by job** [jasdips/rdap-rpki#1]
Similar to ASPA, BGPsec router keys are asserted by the AS Holder. Unlike ASPA and SPL, BGPsec is a full standard. Can you add BGPsec along side ROAs and ASPAs in this draft?

**Comment by jasdips** [comment]
Good idea, Job! Will incorporate it. Thanks for the suggestion.

**Comment by jasdips** [comment]
Created PR: https://github.com/jasdips/rdap-rpki/pull/3.
