### ISSUE TITLE
Delegated RPKI

### ISSUE THREAD

**Issue by jasdips** [jasdips/rdap-rpki#2]
What registration info can be presented through RDAP for the delegated RPKI profile objects?

**Comment by ties** [comment]
Not much. For ripe ncc system: the repo urls, the public key, the
resources. Other details are not kept (without parsing) by the CA system.

**Comment by jasdips** [comment]
Thanks, Ties.

**Comment by anewton1998** [comment]
Though you may not immediately take advantage of it, being able to represent the roas of delegated repos is beneficial for troubleshooting. That would require the RIRs to suck in those RPKI objects but it is very useful for troubleshooting purposes. I used JDR for this all the time. (unfortunately, JDR seems to be offline these days).

**Comment by ties** [comment]
@anewton1998 I get the value of it. However, the RDAP server would end up presenting data for which the server (+ it's operating environment) is authoritative as well as data where it is not.

Would this be surprising for RDAP? Or OK?

**Comment by anewton1998** [comment]
As long as a client can determine where the data came from and where it resides, I think it should be ok. I don't know if RIRs will use such a feature immediately, but I wouldn't want to close it off in the spec.

**Comment by ties** [comment]
> As long as a client can determine where the data came from and where it resides, I think it should be ok. I don't know if RIRs will use such a feature immediately, but I wouldn't want to close it off in the spec.

That is also valid. I just do not like mixing close-to-authoritative and non-authoritative data in one endpoint.
