### ISSUE TITLE
Resource Certificate object class

### ISSUE THREAD

**Issue by jasdips** [jasdips/rdap-rpki#6]
@anewton1998, @ties, @tomhrr 

[Ties earlier said](https://github.com/jasdips/rdap-rpki/pull/3#issuecomment-2207297200): "But this extension probably should try to model all the certificates that can be expressed in RPKI."

IMO, that's a pretty interesting insight! After all, [RFC 6487](https://www.rfc-editor.org/rfc/rfc6487.html) allows resource certificates to be created with a combination of IP and/or AS resources. That way, such a certificate could be used to assert about a ROA, an ASPA, or be used to securely emit route advertisements for AS(es) from a BGPSec router. How about we replace the BGPSec Router Certificate object class with a more generic Resource Certificate object class while evolving the search a bit more (by IP, in addition to by ASN and other already defined search criteria)?

**Comment by ties** [comment]
@jasdips that is an interesting avenue! I had not though about broading it this far (all "sub-certificates"). Modeling how we incorporate delegated CA certificates may be a good challenge though.

Another difficult case might be "inherited" resources. But I do not think these apply in the context were are modelling.

**Comment by jasdips** [comment]
> @jasdips that is an interesting avenue! I had not though about broading it this far (all "sub-certificates"). Modeling how we incorporate delegated CA certificates may be a good challenge though.

Yah, a more generic Resource Certificate object class could prove more useful. Emulating how IPs are represented as CIDRs, we could do ranges for ASNs to shorten that array. (This is how the [IANA RDAP Bootstrap files](https://data.iana.org/rdap/) for IPs and ASNs do.) Should I try hashing out the Resource Certificate object class? :)

> Another difficult case might be "inherited" resources. But I do not think these apply in the context were are modelling.

Yep.

**Comment by jasdips** [comment]
I asked Mark about this. He suggested that, for now, just showing resource certificates related with the ROA, ASPA, and BGPSec Router Certificate profiles should be ok.

**Comment by ties** [comment]
On one hand I see that. On the other hand there is a unified way to model
the authoritative data from delegated CAs and the other data for CA certs
under a CA.

Lets see.

I will notngo to Vancouver, but otherwise this would be a perfect topic to
discuss.
