### ISSUE TITLE
Use different acronym than INR

### ISSUE THREAD

**Issue by job** [jasdips/rdap-rpki#7]
I think “INR” or “INRs” is commonly understood to mean “Internet Number Resource”, especially in context of RPKI. Redefining it as Internet Number *Registry* might cause confusion. 

Perhaps Internet Number Resource Registry (INRR) is better?

**Comment by anewton1998** [comment]
RFC 7020 talks about Internet Number Registry System referring to the whole set. But I agree that it can be confusing. INRR sounds good to me and we should explain the difference.

**Comment by jasdips** [comment]
PR #8 took care of it.
